version: '3.7'
services:
  booking-service:
    image: booking
    stdin_open: true
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3002: 3002
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongodb:
    image: mongo:latest
    ports:
      - 27017: 27017
    volumes:
      - data:/data/db
  volumes:
    mongo-data:
      driver: local


  # docker-compose up
  # docker-compose stop
  # docker-compose down

  # docker ps
  #docker stop (container id)
 



