version: '3.7'
services:
  web:
    image: node:10.15.3
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.3



# docker-compose up
# docker-compose stop
# docker-compose down