version: "3"
services:
  booking:
    container_name: booking-service
    image: hannahmanfredi/booking-service
    restart: always
    ports:
      - "80:3002"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db




