version: "3"
services:
  apps:
    container_name: booking
    image: hannahmanfredi/booking-service
    restart: always
    build: .
    ports:
      - "80:3002"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /appBooking/data/db





