version: "3"
services:
  app:
    container_name: booking
    restart: always
    build: .
    stdin_open: true
    tty: true
    ports:
      - "3002:3002"
    volumes:
      - .:/app-booking
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db




